export default [
  'Accounting',
  'American Studies',
  'Anthropology',
  'Art',
  'Art History',
  'Biology',
  'Business Studies',
  'Chemistry',
  'Computer Science',
  'Criminology',
  'Drama',
  'Economics',
  'English',
  'English Literature',
  'Film Studies',
  'Finance',
  'French',
  'Geography',
  'German',
  'History',
  'Journalism',
  'Law',
  'Marketing',
  'Maths',
  'Media',
  'Music',
  'Nursing',
  'Philosophy',
  'Physics',
  'Politics',
  'Psychology',
  'Religious Studies',
  'Sociology',
  'Spanish',
];
